apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-job
spec:
  template:
    metadata:
      name: etcd-job
    spec:
      containers:
      - name: etcd-job
        image: tenstartups/etcdctl
        env:
          - name: ETCDCTL_ENDPOINT
            value: 'http://example-etcd-cluster-client-service:2379'
        command: ["etcdctl",  "mkdir", "pod-list"]
      restartPolicy: Never